### ISSUE TITLE
UIButton: Using gradients + state colours broken.

### ISSUE THREAD

**Issue by squarefrog** [tombenner/nui#247] opened 2014-05-10 21:13 UTC
I've just noticed an odd behaviour while I'm writing the first set of tests. If you set a button gradient colour, then set block colours for button states, then the clipping is wrong. Here is the theme:

    Button {
        background-color-top: @redColor;
        background-color-bottom: @greenColor;
        background-color-disabled: @blueColor;
        background-color-highlighted: @yellowColor;
        background-color-selected: @cyanColor;
        border-color: @primaryBorderColor;
        border-width: @primaryBorderWidth;
        font-color: @secondaryFontColor;
        font-color-highlighted: #666666;
        font-name: @primaryFontName;
        font-size: 17;
        height: 37;
        corner-radius: 8;
        padding: 7;
    }

Normal state:
![testbutton 2x](https://cloud.githubusercontent.com/assets/343450/2937109/d351bfd0-d887-11e3-8bef-8445e776ebd2.png)

Disabled state:
![testbuttondisabled 2x](https://cloud.githubusercontent.com/assets/343450/2937111/dbef7556-d887-11e3-817c-9dd93bded66d.png)

Highlighted state:
![testbuttonhighlighted 2x](https://cloud.githubusercontent.com/assets/343450/2937113/e46bc7d4-d887-11e3-93c7-555278e43902.png)

Selected state:
![testbuttonselected 2x](https://cloud.githubusercontent.com/assets/343450/2937114/eade3962-d887-11e3-8977-6be754fd0b89.png)

I know it's ugly but its purely a test :)

**Comment by timbodeit** [comment] 2015-11-11 00:47
Should be fixed by 32b8a338b309c9cafdca8021184a298330ba4a6f

**Closed by timbodeit** 2015-11-11 00:47 UTC

**Comment by timbodeit** [comment] 2015-11-11 00:54
Note: Assumed fix is a year older than the issue. Tested this by plugging the given theme into the demo project though. Could not reproduce issue anymore.
