### ISSUE TITLE
Tint color?

### ISSUE THREAD

**Issue by markst** [tombenner/nui#272] opened 2014-08-28 23:47 UTC
Since iOS7 it's possible to set the tint color of views.
Is it possible to define the global tint color and of certain views?

**Comment by frapaa** [comment] 2015-02-27 07:49
You can set global tint color programatically with `[[UIApplication sharedApplication] keyWindow].tintColor = [Color redColor]`

Unfortunately, there's no way to load a specific color from the stylesheet, but you could add a class

```
ThemeColors {
    tint-color: #FF0000;
}
```
Then use ``[[UIApplication sharedApplication] keyWindow].tintColor = [NUISettings getColor:@"tint-color" withClass:@"ThemeColors"]`

**Comment by timbodeit** [comment] 2015-11-19 16:23
Duplicate of #223.

**Closed by timbodeit** 2015-11-19 16:23 UTC
Labels: duplicate
