### ISSUE TITLE
Unable to ignore: UITableViewRowAction buttons

### ISSUE THREAD

**Issue by SteveNewhouse** [tombenner/nui#299] opened 2015-06-26 13:52 UTC
There does not seem to be any way to avoid applying the Button style to UITableViewRowActions, (the slideout buttons).  I have tried adding this to the exclude / exclude-subviews attributes of Button NUI class, but that did not work.  Also looked for a way to set nuiClass to "none" programmatically but that also did not work (and may require accessing private classes within UITableViewRowAction.

Anyone know a solution here other than not using Button as a style class?

![image](https://cloud.githubusercontent.com/assets/1760211/8378625/bff07d28-1be8-11e5-94bf-307b28666741.png)

**Comment by frapaa** [comment] 2015-07-06 19:10
Using ```exclude-subviews: UITableViewCell;``` under ```Button``` should work (it does for me). But there seems to be an issue if you add multiple excludes, they will all fail. See #269 and #224.

**Comment by timbodeit** [comment] 2015-11-18 14:57
Assumed duplicate of #224 and #269. Fixed by #312.
Please reopen if this is indeed a separate issue.

**Closed by timbodeit** 2015-11-18 14:57 UTC
