### ISSUE TITLE
override_didMoveToWindow infinite loop when testing with XCode test framework

### ISSUE THREAD

**Issue by rhfung** [tombenner/nui#177] opened 2013-10-04 23:40 UTC
The method `override_didMoveToWindow` in UINavigationBar+NUI.m gets into an infinite recursion when running an app for a Test build.

     - (void)override_didMoveToWindow
     {
         if (!self.nuiIsApplied) {
             [self applyNUI];
         }
         [self override_didMoveToWindow];
     }

The method does not have a mechanism to stop itself from recursion. What would be the preferred way to fix this problem? A known workaround is to comment out NUI for a test build and then re-enable it afterward. ifdef does not work because macros are defined separately for each target.

**Comment by intonarumori** [comment] 2015-04-10 08:50
Related issue here: https://github.com/tombenner/nui/issues/154

**Comment by timbodeit** [comment] 2015-11-19 21:55
Closing as duplicate of #154

**Closed by timbodeit** 2015-11-19 21:55 UTC
